spring:
  liquibase:
    enabled: true
    change-log: classpath:deal/liquibase/changelog.xml
    default-schema: deal_schema
    liquibase-schema: liquibase_schema
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: deal_schema
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/crypto-exchange
server:
  port: 8083

