crypto-exchange:
  kafka:
    request-topic: notification-topic
spring:
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: crypto-exchange
  mail:
    host: smtp.rambler.ru
    port: 2525
    username: spring.mail@rambler.ru
    password: 1z2x3c4vMail
    properties:
      mail:
        store:
          protocol: pop3
        smtp:
          connecttimeout: 5000
          timeout: 3000
          writetimeout: 5000
          starttls:
            enable: true
          auth: true
  datasource:
    url: jdbc:h2:mem:testdb
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/crypto-exchange
server:
  port: 8085
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: metrics,health
