server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: customers
          uri: http://localhost:8081/
          predicates:
            - Path=/customers/**
        - id: accounts
          uri: http://localhost:8082/
          predicates:
            - Path=/accounts/**
        - id: deals
          uri: http://localhost:8083/
          predicates:
            - Path=/deals/**
        - id: auctions
          uri: http://localhost:8084/
          predicates:
            - Path=/auctions/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - Authorization
