server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://localhost:8081/
          predicates:
            - Path=/customers/**
        - id: customer
          uri: http://localhost:8082/
          predicates:
            - Path=/accounts/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - Authorization
