server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/crypto-exchange
      client:
        registration:
          keycloak:
            client-id: crypto-exchange-client
            client-secret: n96b2H84sWgdq2WyTFai6w0MQ4Ck7tW7
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/crypto-exchange
            user-name-attribute: preferred_username

